-- Builds a readable DDL snapshot of the production database: every public table
-- with its columns, constraints, indexes, RLS policies, triggers and grants, plus
-- views, functions (and who may execute them), enums, storage buckets and
-- policies, triggers on auth tables, and the realtime publication.
--
-- Read-only: every statement is a SELECT against the system catalogs.
-- Run by scripts/db/snapshot-schema.mjs, which writes supabase/schema.sql.
-- Output is ordered by name so a refresh only diffs what actually changed.

with
all_privs as (
  -- how many table privileges make up ALL on this server (7 before PG17, 8 after)
  select count(*) as n from aclexplode(acldefault('r', 10::oid))
),
grants as (
  select g.oid, string_agg(g.grantee || ': ' || g.privs, '; ' order by g.grantee) as line
  from (
    select c.oid,
      coalesce(r.rolname, 'PUBLIC') as grantee,
      case when count(*) = (select n from all_privs) then 'ALL'
           else string_agg(a.privilege_type, ', ' order by a.privilege_type) end as privs
    from pg_class c
    cross join lateral aclexplode(c.relacl) a
    left join pg_roles r on r.oid = a.grantee
    where c.relnamespace = 'public'::regnamespace
      and c.relkind in ('r', 'p', 'v', 'm')
      and coalesce(r.rolname, 'PUBLIC') not in ('postgres', 'supabase_admin')
    group by c.oid, coalesce(r.rolname, 'PUBLIC')
  ) g
  group by g.oid
),
tbl as (
  select c.oid, c.relname, c.relrowsecurity, c.relforcerowsecurity
  from pg_class c
  where c.relnamespace = 'public'::regnamespace
    and c.relkind in ('r', 'p')
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
),
cols as (
  select a.attrelid as oid,
    string_agg(
      format('  %I %s', a.attname, format_type(a.atttypid, a.atttypmod))
      || case a.attidentity when 'a' then ' GENERATED ALWAYS AS IDENTITY'
                            when 'd' then ' GENERATED BY DEFAULT AS IDENTITY' else '' end
      || case when a.attgenerated = 's' then ' GENERATED ALWAYS AS (' || pg_get_expr(d.adbin, d.adrelid) || ') STORED'
              when d.adbin is not null then ' DEFAULT ' || pg_get_expr(d.adbin, d.adrelid)
              else '' end
      || case when a.attnotnull then ' NOT NULL' else '' end,
      E',\n' order by a.attnum) as body
  from pg_attribute a
  join tbl t on t.oid = a.attrelid
  left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
  where a.attnum > 0 and not a.attisdropped
  group by a.attrelid
),
cons as (
  select con.conrelid as oid,
    string_agg(format('  CONSTRAINT %I %s', con.conname, pg_get_constraintdef(con.oid, true)), E',\n'
      order by case con.contype when 'p' then 0 when 'u' then 1 when 'f' then 2 when 'c' then 3 else 4 end, con.conname) as body
  from pg_constraint con
  join tbl t on t.oid = con.conrelid
  where con.contype in ('p', 'u', 'f', 'c', 'x')
  group by con.conrelid
),
idx as (
  -- indexes that are not already shown as a PRIMARY KEY, UNIQUE or EXCLUDE constraint
  select i.indrelid as oid, string_agg(pg_get_indexdef(i.indexrelid) || ';', E'\n' order by ic.relname) as body
  from pg_index i
  join tbl t on t.oid = i.indrelid
  join pg_class ic on ic.oid = i.indexrelid
  where not exists (
    select 1 from pg_constraint con
    where con.conindid = i.indexrelid and con.conrelid = i.indrelid and con.contype in ('p', 'u', 'x')
  )
  group by i.indrelid
),
pol as (
  select format('%I.%I', p.schemaname, p.tablename) as rel,
    string_agg(
      format('CREATE POLICY %I ON %I.%I AS %s FOR %s TO %s',
             p.policyname, p.schemaname, p.tablename, p.permissive, p.cmd, array_to_string(p.roles, ', '))
      || coalesce(E'\n  USING (' || p.qual || ')', '')
      || coalesce(E'\n  WITH CHECK (' || p.with_check || ')', '') || ';',
      E'\n' order by p.policyname) as body
  from pg_policies p
  group by p.schemaname, p.tablename
),
trg as (
  select t.tgrelid as oid, string_agg(pg_get_triggerdef(t.oid, true) || ';', E'\n' order by t.tgname) as body
  from pg_trigger t
  where not t.tgisinternal
  group by t.tgrelid
),
table_blocks as (
  select string_agg(
    concat_ws(E'\n',
      format('CREATE TABLE public.%I (', t.relname),
      concat_ws(E',\n', cols.body, cons.body),
      ');',
      idx.body,
      case when t.relrowsecurity then format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t.relname)
           else format('-- WARNING: RLS is DISABLED on public.%I', t.relname) end,
      case when t.relforcerowsecurity then format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;', t.relname) end,
      pol.body,
      trg.body,
      '-- grants: ' || coalesce(g.line, 'owner only'),
      '-- comment: ' || obj_description(t.oid, 'pg_class')
    ), E'\n\n' order by t.relname) as body
  from tbl t
  left join cols on cols.oid = t.oid
  left join cons on cons.oid = t.oid
  left join idx on idx.oid = t.oid
  left join pol on pol.rel = format('%I.%I', 'public', t.relname)
  left join trg on trg.oid = t.oid
  left join grants g on g.oid = t.oid
),
view_blocks as (
  select string_agg(
    concat_ws(E'\n',
      format('CREATE %sVIEW public.%I%s AS',
             case when c.relkind = 'm' then 'MATERIALIZED ' else '' end, c.relname,
             coalesce(' WITH (' || array_to_string(c.reloptions, ', ') || ')', '')),
      rtrim(pg_get_viewdef(c.oid, true)),
      '-- grants: ' || coalesce(g.line, 'owner only')
    ), E'\n\n' order by c.relname) as body
  from pg_class c
  left join grants g on g.oid = c.oid
  where c.relnamespace = 'public'::regnamespace
    and c.relkind in ('v', 'm')
    and not exists (select 1 from pg_depend d where d.objid = c.oid and d.deptype = 'e')
),
fn_blocks as (
  select string_agg(
    concat_ws(E'\n',
      rtrim(pg_get_functiondef(p.oid), E'\n') || ';',
      '-- execute: ' || case when p.proacl is null then 'PUBLIC (default)' else coalesce(
        (select string_agg(coalesce(r.rolname, 'PUBLIC'), ', ' order by coalesce(r.rolname, 'PUBLIC'))
         from aclexplode(p.proacl) a
         left join pg_roles r on r.oid = a.grantee
         where a.privilege_type = 'EXECUTE'
           and coalesce(r.rolname, 'PUBLIC') not in ('postgres', 'supabase_admin')),
        'owner only') end
    ), E'\n\n' order by p.proname, pg_get_function_identity_arguments(p.oid)) as body
  from pg_proc p
  where p.pronamespace = 'public'::regnamespace
    and p.prokind in ('f', 'p')
    and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
),
enum_blocks as (
  select string_agg(
    format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
      (select string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder)
       from pg_enum e where e.enumtypid = t.oid)),
    E'\n' order by t.typname) as body
  from pg_type t
  where t.typnamespace = 'public'::regnamespace and t.typtype = 'e'
),
storage_block as (
  select concat_ws(E'\n\n',
    (select string_agg(
       format('-- bucket %s: public=%s, file_size_limit=%s, allowed_mime_types=%s',
              b.id, b.public, coalesce(b.file_size_limit::text, 'none'),
              coalesce(array_to_string(b.allowed_mime_types, ', '), 'any')),
       E'\n' order by b.id)
     from storage.buckets b),
    (select string_agg(pol.body, E'\n\n' order by pol.rel) from pol where pol.rel like 'storage.%')
  ) as body
),
auth_block as (
  select string_agg(pg_get_triggerdef(t.oid, true) || ';', E'\n' order by c.relname, t.tgname) as body
  from pg_trigger t
  join pg_class c on c.oid = t.tgrelid
  where c.relnamespace = 'auth'::regnamespace and not t.tgisinternal
),
realtime_block as (
  select '-- supabase_realtime publication: '
    || string_agg(format('%I.%I', pt.schemaname, pt.tablename), ', ' order by pt.schemaname, pt.tablename) as body
  from pg_publication_tables pt
  where pt.pubname = 'supabase_realtime'
),
ext_block as (
  select string_agg(format('-- %s %s (schema %s)', e.extname, e.extversion, n.nspname), E'\n' order by e.extname) as body
  from pg_extension e
  join pg_namespace n on n.oid = e.extnamespace
)
select concat_ws(E'\n\n',
  '-- ==== Extensions ====', (select body from ext_block),
  '-- ==== Enums ====', (select body from enum_blocks),
  '-- ==== Tables (public) ====', (select body from table_blocks),
  '-- ==== Views (public) ====', (select body from view_blocks),
  '-- ==== Functions (public) ====', (select body from fn_blocks),
  '-- ==== Storage ====', (select body from storage_block),
  '-- ==== Triggers on auth tables ====', (select body from auth_block),
  '-- ==== Realtime ====', (select body from realtime_block)
) as ddl;
