// Writes supabase/schema.sql, a read-only snapshot of the production schema.
// The query lives in scripts/db/schema-snapshot.sql and runs through the
// Supabase Management API (`supabase db query --linked`), so it needs neither
// Docker nor the database password. The repo is public, so the script refuses
// to write when the result looks partial or contains something credential-like.
import { execFileSync } from 'node:child_process';
import { renameSync, writeFileSync } from 'node:fs';

const QUERY_FILE = 'scripts/db/schema-snapshot.sql';
const OUTPUT_FILE = 'supabase/schema.sql';
const MAX_OUTPUT_BYTES = 64 * 1024 * 1024;
const OBJECT_LABEL_LENGTH = 100;

// Every healthy snapshot contains these; a missing one means a partial result.
const REQUIRED_MARKERS = ['CREATE TABLE public.profiles (', 'CREATE POLICY', '-- ==== Storage ===='];

const SECRET_PATTERNS = [
  { name: 'JWT', pattern: /eyJ[\w-]{10,}\.[\w-]{10,}\.[\w-]{10,}/ },
  { name: 'Supabase secret key', pattern: /sb_secret_[\w-]{10,}/ },
  { name: 'secret API key', pattern: /\bsk_(live|test)_\w{10,}/ },
  { name: 'Bearer token', pattern: /Bearer\s+[\w.~+/-]{20,}/ },
];

const HEADER = [
  '-- Generated by `npm run db:schema` from the production database. Do not edit by hand.',
  `-- Source query: ${QUERY_FILE}. Schema changes go through supabase/migrations.`,
].join('\n');

function runQuery() {
  const stdout = execFileSync(
    'supabase',
    ['db', 'query', '--linked', '--agent', 'no', '--output-format', 'json', '-f', QUERY_FILE],
    { encoding: 'utf8', maxBuffer: MAX_OUTPUT_BYTES, stdio: ['ignore', 'pipe', 'inherit'] },
  );
  const rows = JSON.parse(stdout);
  const ddl = Array.isArray(rows) ? rows[0]?.ddl : undefined;
  if (typeof ddl !== 'string' || ddl.length === 0) {
    throw new Error('the snapshot query returned no DDL');
  }
  return ddl;
}

function assertComplete(ddl) {
  const missing = REQUIRED_MARKERS.filter((marker) => !ddl.includes(marker));
  if (missing.length > 0) {
    throw new Error(`the snapshot looks partial, missing: ${missing.join(' | ')}`);
  }
}

// Names the object that holds each hit (the nearest CREATE line above it),
// never the matched value itself.
function findSecrets(ddl) {
  const lines = ddl.split('\n');
  return lines.flatMap((line, index) => {
    const hit = SECRET_PATTERNS.find(({ pattern }) => pattern.test(line));
    if (!hit) return [];
    const owner = lines.slice(0, index + 1).findLast((candidate) => candidate.startsWith('CREATE'));
    return [`${hit.name} in: ${(owner ?? 'unknown object').slice(0, OBJECT_LABEL_LENGTH)}`];
  });
}

function main() {
  const ddl = runQuery();
  assertComplete(ddl);
  const secrets = findSecrets(ddl);
  if (secrets.length > 0) {
    throw new Error(`refusing to write, credential-like values found:\n  ${secrets.join('\n  ')}`);
  }
  const tmpFile = `${OUTPUT_FILE}.tmp`;
  writeFileSync(tmpFile, `${HEADER}\n\n${ddl}\n`);
  renameSync(tmpFile, OUTPUT_FILE);
  console.log(`Wrote ${OUTPUT_FILE} (${ddl.split('\n').length} lines).`);
}

try {
  main();
} catch (error) {
  console.error(`db:schema failed: ${error instanceof Error ? error.message : String(error)}`);
  process.exit(1);
}
